version: "3"

# https://github.com/yifangd/docker-browser-tigervnc
services:
  browser-tigervnc:
    container_name: browser-tigervnc
    image: yifang/browser-tigervnc:latest
    # revert back to default via proxy, to simplify the dependency
    #network_mode: "container:gluetun"
    hostname: browser-tigervnc
    #network_mode: host
    environment:
        - "PULSE_SERVER=192.168.22.9"
    ports:
        - "127.0.0.1:5909:5908/tcp"
    # Volumes store your data between container upgrades
    volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - './data/live:/home/browser'
        - '/f/rt/q:/home/browser/Downloads/q'
        - '/f/i/tbd-gphotos-amosch:/home/browser/Downloads/tbd-gphotos-amosch'
    restart: unless-stopped

