version: "3"

# https://github.com/yifangd/chrome
services:
  chrome:
    container_name: chrome
    hostname: chrome
    image: yifang/chrome:latest
    ports:
        - "5909:5900/tcp"
    # Volumes store your data between container upgrades
    volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - '/keep/docker-chrome-data/live:/home/chrome'
    restart: unless-stopped

