version: "3"

# https://github.com/yifangd/docker-browser-tigervnc
services:
  browser-tigervnc:
    container_name: browser-tigervnc
    hostname: browser-tigervnc
    image: yifang/browser-tigervnc:latest
    ports:
            - "5909:5900/tcp"
    # Volumes store your data between container upgrades
    volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - '/keep/docker-browser-tigervnc-data/live:/home/browser'
    restart: unless-stopped

